baseURL = 'https://shourai.github.io'
languageCode = 'en-us'
title = "Betsuni"
theme =  "PaperMod"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  defaultTheme = 'dark'
  comments = true
